// This is where it all goes :)
//= require "jquery"
//= require "vendor/ace/ace"
//= require "vendor/ace/theme-monokai"
//= require "vendor/ace/mode-javascript"
//= require "editor"
//= require "parser"
//= require "mips_pipeline"
//= require "pipeline_creation"
//= require "memory"
